version: '3.9'

services:
  mysql:
    container_name: auth-api-db
    image: mysql:8.0.32
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - MYSQL_DATABASE=auth_api
    ports:
      - "3306:3306"
    networks:
      - auth-api

networks:
  auth-api:
