server:
  port: 8080
  servlet:
    context-path: /api/v1

jwt:
  issuer: auth-api
  expiry: 36000
  key:
    private: ${key.private}
    public: ${key.public}

spring:
  datasource:
    url: jdbc:mysql://${mysql.url}/${mysql.schema}
    username: ${mysql.username}
    password: ${mysql.password}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
    defaultModelsExpandDepth: -1
