name: CI/CD Pipeline

on:
  push:
    branches:
      - 'release/**'
      - 'main'
      - 'hotfix/**'
      - 'develop'
  workflow_dispatch:

jobs:
  test:
    name: Test Runner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt
      - name: Run Tests
        run: ./gradlew test
  build-deploy:
    name: Build and Deploy Runner
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Run Build
        uses: gradle/gradle-build-action@v2.6.0
        with:
          arguments: clean build -x test
      - name: Set Build Tag
        run: echo BUILD_TAG=$(echo ${{ github.head_ref || github.ref_name }} | sed "s,/,_,g")-${{ github.run_number }} >> $GITHUB_ENV
      - name: Show Build Tag
        run: echo $BUILD_TAG
      - name: Login to DockerHub
        uses: docker/login-action@v2.2.0
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4.1.1
        with:
          context: .
          push: true
          build-args: VERSION=$BUILD_TAG
          tags: ${{ env.DOCKERHUB_IMAGE }}:$BUILD_TAG
