name: CI/CD Pipeline

on:
  push:
    branches:
      - 'release/**'
      - 'main'
      - 'hotfix/**'
      - 'develop'
  workflow_dispatch:

jobs:
  test:
    name: Test Runner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt
      - name: Run Tests
        run: ./gradlew test
  deploy:
    name: Deploy Runner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: adopt
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Run Build
        uses: gradle/gradle-build-action@v2.6.0
        with:
          arguments: clean build -x test
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: 5.x
          preferLatestVersion: true
      - name: Set Version
        uses: gittools/actions/gitversion/execute@v0
        with:
          useConfigFile: true
      - name: Show Version
        run: |
          VERSION=$(echo $GITVERSION_SEMVER | sed 's/-[a-zA-Z]*\./-/')
          echo "Version ---> $VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Set Build Tag
        run: echo BUILD_TAG=$(echo ${{ github.head_ref || github.ref_name }} | sed "s,/,_,g")-${{ github.run_number }}-${{ env.VERSION }} >> $GITHUB_ENV
      - name: Show Build Tag
        run: echo "Tag ---> ${{ env.BUILD_TAG }}"
      - name: Login to DockerHub
        uses: docker/login-action@v2.2.0
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: Push Image
        uses: docker/build-push-action@v4.1.1
        with:
          context: .
          push: true
          build-args: VERSION=${{ env.BUILD_TAG }}
          tags: ${{ vars.DOCKERHUB_IMAGE }}:${{ env.BUILD_TAG }}
